### ISSUE TITLE
[BUG] Wallet says token active but actually no trust was set

### ISSUE THREAD

**Issue by Marec4** [casinocoin/tokenwallet-mobile#230] opened 2020-06-16 11:54 UTC
**Describe the bug**
Added CR8 token to activated CSC account. It says active in the wallet but actually no trust was set on the chain.

https://csc.observer/account/c72d1YmRMqXP2J3coU66MxBgsEYfksWLo

iPhone XS, iOS 13.4.1, wallet 5.0.1

![2020-06-16](https://user-images.githubusercontent.com/25827470/84770914-20bd4a00-afe1-11ea-83fc-c13cae2bc85f.png)

**Comment by t3nshi** [comment] 2020-07-13 15:10
I would need a bit more information. That's why we provide the issue templates so you know how to provide information enough to reproduce this issue. I tried in the past two weeks on different devices and I am still unable to reproduce this.

**Comment by Marec4** [comment] 2020-07-14 09:37
It happened just once and I couldn't reproduce it either again. Didn't do anything unusual just added CR8 to different CSC accounts (I have 4 accounts in the wallet and this happened when adding CR8 to second CSC account).

**Comment by t3nshi** [comment] 2020-08-11 21:54
So long and I still was not able to reproduce this.... I will close this for the time being, hopefully when the issue appears again we will have more info about it.

**Closed as completed by t3nshi** 2020-08-11 21:54 UTC
Labels: bug, question
