### ISSUE TITLE
[BUG] Scanning QR-code doesn't work

### ISSUE THREAD

**Issue by Marec4** [casinocoin/tokenwallet-mobile#69] opened 2020-01-21 14:17 UTC
**Describe the bug**
When trying to send coins and scan QR-code, the scanning works but nothing is populated into "To account" field. Also, a Yellow Warning!! is displayed at the bottom of the screen but can't see additional information about it.

**To Reproduce**
1. Go to Wallet Tab
2. Choose Send coins 
3. Click on SCAN

**Expected behavior**
A valid CasinoCoin account id is populated into "To account" field and there's additional information about the warning.

**Screenshots**
![Screenshot_20200121-161042_Token_Wallet 1](https://user-images.githubusercontent.com/25827470/72811818-1339a900-3c69-11ea-800f-c54f84edb98d.jpg)
![Screenshot_20200121-160832_Token_Wallet 1](https://user-images.githubusercontent.com/25827470/72811840-1d5ba780-3c69-11ea-8763-af489dce71d1.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy J3 2017
 - OS: Android
 - OS Version 8
 - App Version 0.1.5

**Comment by t3nshi** [comment] 2020-01-21 16:30
Hi there, thanks for the information, though, I was trying to reproduce the issue, and I could not. I created a QR and then scan it from the send form and it was populated, even the label and destinationTag added got populated on the form... There might be an additional step you didn't mention that it's crucial for the bug to show up... or it may be that you are creating the QR by other means not supported. By the way, how are you creating the QR?

**Comment by Marec4** [comment] 2020-01-21 17:21
QR is from iOS mobile wallet. 

Tried again: closed the wallet completely, opened app and signed in with my PIN, Wallet tab, chose send coins and then Scan. Still the same.

**Comment by t3nshi** [comment] 2020-01-21 18:44
thanks for the quick response... can you tell me what iOS mobile wallet are you using? version and what device is deployed in? 
that might be the reason it is not working.

**Comment by Marec4** [comment] 2020-01-21 18:45
Version 4.1.2, iOS 13.3, iPhone 6s

**Comment by Marec4** [comment] 2020-01-21 18:48
Also tried to scan random address in explorer, the results are the same.

**Comment by t3nshi** [comment] 2020-01-21 21:08
Then that's it... a random QR does not work, we are currently only supporting the QR generated on a token wallet, like the one you are using for scanning or like the new version for desktop. Older wallet QRs or plain address QRs are not supported. Never the less is quite simple to use it. If you scan that QR with the app it will get passed to the clipboard. So you just paste it on the To account field. The problem is that this QR doesn't contain the entire object, it only has the account ID. Download the last version of the Desktop wallet and you will be able to test with a proper QR. I'll be closing this as this is not really an issue.

**Comment by Marec4** [comment] 2020-01-22 06:57
Yes, working with a new wallet. As I understand (tested this with bitrue) currently this doesn't support exchange addresses. When we release the wallet to public and it stays this way, this will cause a lot of negative feedback.

If it is already in the clipboard, would it be impossible to implement the population to the correct field?

**Comment by t3nshi** [comment] 2020-01-22 20:52
Please @ajochems take a look at this and let us know how this is in the roadmap

**Comment by t3nshi** [comment] 2020-01-23 17:14
Let me try something by @ajochems recommendation, will report back when I've been able to test it.

**Comment by t3nshi** [comment] 2020-01-28 20:06
I made some changes and now I added support for QR codes where the encoded text is a valid CSC or token accountID. Try it on the next upcoming version and let me know.

**Closed as completed** 2020-01-28 21:50 UTC
Labels: bug, question, in progress
