### ISSUE TITLE
[BUG] gesture swipe menu and back button takes you to login when menu open

### ISSUE THREAD

**Issue by justfordaniel** [casinocoin/tokenwallet-mobile#95] opened 2020-01-26 21:55 UTC
![Screenshot_ui](https://user-images.githubusercontent.com/57195813/73142415-378cef80-4086-11ea-9761-e4385c7e9b67.png)

**Is your feature request related to a problem? Please describe.**
after pressing the top menu it should gesture to close.  if you press the back button on your phone once it logs you out but keeps the menu open also which is a bit frustrating.  

**Describe the solution you'd like**
menu needs gesture close and logo in menu should take you somewhere.  also back button once should take you to dashboard, twice could log out but once to log out is annoying.  thanks

it would not let me put this in feature req but i guess it could be in here maybe too

**Comment by t3nshi** [comment] 2020-01-27 13:22
thanks a lot for your take on this. I don't know how familiar you are with UX design, but currently many apps and designs are getting rid of swipe menu open and close as it is considered by many as bad UI design, in the way that interferes with any swipe actions we have implemented on the app and gets confusing for many users. It tends to happens that way, and you are going to find people in favor and against this. We are not using this because we have some swipe actions implemented in app. The current standard encourages that menu should open with buttons and in case of overlay meny like this, just tapping outside  the menu closes the menu. Additionally this is a duplicate of a previous issue. We appreciate that you take your time to create an issue, but to avoid some overhead and your issue to be quickly dismissed, I suggest you browse through previous issues first so you don't bring duplicates, also try to fill in the template following the directions provided, so it is clear and concise. It might be better to create separate issues when they are different.  For instance I think I will explore the back button bug that you mentioned here instead of closing this. 
Thanks in advance.

**Comment by t3nshi** [comment] 2020-01-27 13:29
Please check #46 to see if the first part of this issue is the same to what's reported here.

**Comment by t3nshi** [comment] 2020-01-28 22:37
Please check #46 and #105, If you find that your issue is different than those or is still not being addressed please reopen this again. I'm closing it since you are not providing additional information yet.

**Closed as completed by t3nshi** 2020-01-28 22:37 UTC
Labels: bug, duplicate, question
