### ISSUE TITLE
[BUG] General about auto being logged out

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#103] opened 2020-01-27 13:55 UTC
Time out for being logged out after inactivity seems very short.
What is the time set to? Seems like 10 seconds or less.

I have also noticed that after  taken some action I instantly get logged out.
It´s just Boom, and I am out

**Smartphone (please complete the following information):**
 - Device: Honor 8 Lite
 - OS: Android
 - OS Version 8.0.0
 - App Version 0.1.9

**Comment by t3nshi** [comment] 2020-01-27 14:02
We fixed it according to #73 so it should ask you for login any time you put the app on background.  But if you have it on foreground it shouldn't log off so quick. Can you check if that is the case? is it asking for login because your screen was locked or you brought an app to foreground?

**Comment by zenkertA** [comment] 2020-01-27 14:05
Putting the App in the background logs me out.

**Comment by t3nshi** [comment] 2020-01-27 14:35
So you mean it is working as intended... Or not?

**Comment by zenkertA** [comment] 2020-01-27 14:39
As it should if you get logged out when putting the app in the background.
It feels a bit confusing though that it works that way.

**Comment by t3nshi** [comment] 2020-01-27 14:43
So, If you think this is still confusing or it should be handled in a different way, then lets reopen #73 and start a discussion about it. Maybe it should not be that way. But we can figure it out. I will close this as it will be the same discussion.

**Closed as completed by t3nshi** 2020-01-27 14:43 UTC
Labels: bug, duplicate

**Comment by zenkertA** [comment] 2020-01-27 14:52
Being logged out when you put the app in the background is to me very
confusion.
I cannot se the reason for doing it. I have a lot of apps running at the
same time.
Sometimes I need to open another app and when I return to the Token Wallet
I am logged out. Just strange IMHO.
A default Time out time as suggested in #73 is far far better.
Even better a option in Setting for the user to set their own Time Out time
with a Max limit.
