### ISSUE TITLE
[BUG] Top of the full Account info quirky

### ISSUE THREAD

**Issue by zenkertA** [casinocoin/tokenwallet-mobile#104] opened 2020-01-27 14:35 UTC
The text is cut off.
There are lines so I thought I could name the accound. But I cannot.
If you have several accounts, a option to setr one of them as the default accound is needed.

![bild](https://user-images.githubusercontent.com/39646311/73183133-9d2abb80-411a-11ea-8180-c94d369afe90.png)

**Comment by t3nshi** [comment] 2020-01-27 14:40
I can see that... Where do the remaining info of the Bug went? I would like to reproduce this... also this seems like a duplicate of #68 . Is that the case? if it is you can comment there and follow the solution as it will be reported there. If this is something different your full information is the only way to realize your real issue, so please, provide it. Thanks in advance.

**Comment by zenkertA** [comment] 2020-01-27 14:41
Will read up on #63. Thanks for the info. I am a bit lazy sometimes. Sorry
for that.

**Comment by t3nshi** [comment] 2020-01-27 14:48
Don't worry man. I will annoy you sometimes requiring stuff/details/verify as you might prefer me using my time to code than to using it to figure out what or why something is written on an issue.  I will close this so we continue there. If you realize it is different just reopen this.

**Closed as completed by t3nshi** 2020-01-27 14:48 UTC
Labels: bug, duplicate
