### ISSUE TITLE
[BUG] fiat value doesnt change in Dashboard 

### ISSUE THREAD

**Issue by hkooistra** [casinocoin/tokenwallet-mobile#147] opened 2020-02-06 20:44 UTC
**Describe the bug**
When switching in ”settings” the currency from dollar to eur or gbp it doesn't change “fiat value” in Dashboard. 

**To Reproduce**
1. Go to Settings
2. Change currency on dropdown
3. Tap on save settings.
4. Go to dashboard and see still the same fiat value.
(5. It won't change even restarting the app. The setting is applied it is still there)

**Expected behavior**
It should change the fiat value according to my currency selection.

**Screenshots**
none

**Smartphone (please complete the following information):**
 - Device: iphone xr 
 - OS: iOS
 - OS Version 13.3 
 - App Version 0.1.14 CSCLive

**Comment by t3nshi** [comment] 2020-02-07 12:47
Please fill the issue providing the info required so it will be considered. 
I just helped you a bit by editing it myself.  thank you!

**Comment by t3nshi** [comment] 2020-02-07 12:56
It seems like this issue would be a duplicate of #102. When you report a bug please check that it is not already reported. 
Closing this as duplicate continue tracking the progress there.

**Closed as completed by t3nshi** 2020-02-07 12:56 UTC
Labels: bug, duplicate

**Comment by zenkertA** [comment] 2020-02-07 14:23
Been reported in Discord/Preview for IOS version. But Droid is working. So reopen I guess.
