### ISSUE TITLE
[UI-FIX] layout market capital & 24hour volume

### ISSUE THREAD

**Issue by hkooistra** [casinocoin/tokenwallet-mobile#148] opened 2020-02-06 20:50 UTC
**Section or interface element**
Layout issue for market capital & 24h volume

**Reason**
Values below menu/ not visible.

**Description**
The layout needs to be fixed.

**Screenshots**

![91303EB8-4F27-4BE8-B38B-8DE8260CF436](https://user-images.githubusercontent.com/57195781/73977278-5a42c200-492a-11ea-8228-166bf31eb3eb.jpeg)
 on Iphone xr, ios 13.3, wallet version 0.1.14 csclive.

**Comment by t3nshi** [comment] 2020-02-07 13:00
This is already confirmed. I will try to address this for the next release. Thanks for reporting. Please fill the information required properly so we are sure that the problem is clear and can be reproduced. thanks

**Comment by t3nshi** [comment] 2020-02-10 16:57
I will close this since  we have duplicated issues but the other one (see #165 it is a bit more detailed, and better explained. So you can follow up there the status and eventual fix for this. Thanks!

**Closed as completed by t3nshi** 2020-02-10 16:57 UTC
Labels: duplicate, ui-brand
