### ISSUE TITLE
[UI-FIX] some weird text when creating wallet

### ISSUE THREAD

**Issue by justfordaniel** [casinocoin/tokenwallet-mobile#91] opened 2020-01-26 21:28 UTC
![Screenshot_20200126-194821](https://user-images.githubusercontent.com/57195813/73142089-c435ae80-4082-11ea-94f6-c48455564476.png)
**Section or interface element**
some weird text appearing on this page?

**Reason**
Explain why this adjustment improves the look and feel 
or how it will align with branding guidelines

**Description**
A clear and concise description of how the look and feel should be.

**Screenshots**
Illustrate current look and feel. Or provide commented pictures, or 
edited screens to see how it should look like. Be clear about which picture is edited

**Comment by t3nshi** [comment] 2020-01-27 12:54
Please browse through the current issues before opening yours. Keep it in mind for next issues.  this is seems to be a duplicate of #66 please verify if it is, if it's not provide additional information so we understand a bit more your specifics. This should be posted in bug, as it clearly shows something that it's malfunctioning not working.  You are not providing information of your device to help us reproduce your issue. Thanks in advance.

**Comment by t3nshi** [comment] 2020-01-27 12:56
I'm closing this as being a duplicate please provide any additional info in #66. If you realize this bug is different and have different details please reopen providing complete information and details.

**Closed as completed by t3nshi** 2020-01-27 12:56 UTC
Labels: bug, duplicate
