### ISSUE TITLE
[BUG] Recover account by logging in 

### ISSUE THREAD

**Issue by ibanezvaio** [casinocoin/tokenwallet-mobile#74] opened 2020-01-22 22:16 UTC
**Describe the bug**
Device is storing wallet data which is possible to recover after uninstalling

**To Reproduce**
Steps to reproduce the behaviour:
1. Ensure you have a valid wallet with an account
2. Uninstall the app
3. install the app again
4. hit login
5. enter the pin for the old wallet previous to uninstalling

**Expected behaviour**
It should not be possible to login to the old account - the data should have been removed from device storage when the app was uninstalled

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung S6
 - OS: Android
 - OS Version 7.0
 - App Version 0.1.6

**Comment by t3nshi** [comment] 2020-01-22 22:48
That's strange and seems to be the same that @whywefight is experiencing in one device. I will try to reproduce this. Some android setting that @ajochems is going to modify might solve this. Let's see and let us now in the next version.

**Comment by t3nshi** [comment] 2020-01-24 21:38
It seems that this was fixed on version 0.1.8 according to @whywefight .
We are closing this now.

**Closed as completed by t3nshi** 2020-01-24 21:38 UTC
Labels: bug
