### ISSUE TITLE
Fingerprint Sign In

### ISSUE THREAD

**Issue by HolyK1cks** [casinocoin/tokenwallet-mobile#190] opened 2020-02-06 15:28 UTC
Would enjoy a fingerprint scanner sign in option. Enjoy using that over PIN.

**Comment by t3nshi** [comment] 2020-02-20 01:35
this is being worked on for a while now. It is already scheduled and hopefully we will have it for next version 0.1.16 as it was assigned to that milestone. You can follow progress on #134. This will be closed as is a duplicate of previously mention feature request.

**Closed as completed by t3nshi** 2020-02-20 01:35 UTC
Labels: duplicate
