### ISSUE TITLE
[BUG]on and off buttons dont make sense to me?

### ISSUE THREAD

**Issue by justfordaniel** [casinocoin/tokenwallet-mobile#99] opened 2020-01-26 23:15 UTC
**Describe the bug**
the on and off buttons in the top menu dont make sense to me.

if i press the on button it just takes me to the login but im already logged in?  

if i press the off button it just minimises the app and takes it to the login screen.

so essentially both buttons do the same function but the off button also hides the app?

i would personally never use these buttons anyway as to close any app i just swipe it off the screen.  does anyone use a button to close an app on phone?  are they even necessary?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - OS Version [e.g. 8.1]
 - App Version [e.g. 1.0.1]

**Additional context**

**Comment by t3nshi** [comment] 2020-01-27 13:49
Actually there are no on off buttons. What are you writing about. You need to provide complete information (where are you looking at, what are you doing) so it is unambigous and it doesn't become a riddle to understand your bug. Please edit your issue to make yourself clear so I can address your problem properly.  It might help to add screenshots when you don't know how to describe something. Thanks in advance.

**Comment by t3nshi** [comment] 2020-01-28 13:23
This seems to be on the same direction of another issue. Now that I read the other issue this one makes a little more sense. Please checkout this #106 
So I'm closing this for the same reasons there. In case this issue is related to something else and is not currently being addressed, reopen it again, but please, provide enough information, make sure you describe and provide details and fill the required information so we can reproduce your issue and give you a quick response and solution. Thanks.

**Closed as completed by t3nshi** 2020-01-28 13:23 UTC
Labels: bug, invalid, question
