### ISSUE TITLE
[BUG] Field descriptions are not displayed entirely

### ISSUE THREAD

**Issue by Marec4** [casinocoin/tokenwallet-mobile#68] opened 2020-01-21 14:05 UTC
**Describe the bug**
Field descriptions (Account Label, Status and Amount reserved) are not displayed entirely in Wallet Tab and the margin between the field description and the field is too small with the mentioned fields.

**To Reproduce**
1. Open App
2. Login
3. Open Wallet Tab

**Expected behavior**
Field names are displayed in full

**Screenshots**
![Screenshot_20200121-154726_Token_Wallet 1](https://user-images.githubusercontent.com/25827470/72810970-5b57cc00-3c67-11ea-9126-888baa0df09d.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy J3 2017
 - OS: Android
 - OS Version 8
 - App Version 0.1.5

**Additional context**
Probably related to the low screen resolution the Samsung has

**Comment by t3nshi** [comment] 2020-01-21 16:50
I will see what can we do about it, I am trying to get my hands on a smaller device to test this. I tried on many devices and the issue is not showing there.

**Comment by t3nshi** [comment] 2020-01-31 18:18
Some fixes that will be on next version 0.1.11 might solve this. But since I don't have a device that shows this error I would need that the poster try on that version and come back here to report if it's fixed.

**Comment by t3nshi** [comment] 2020-02-04 18:08
So? are the previous fixes for 0.1.11 enough to close this? @Marec4 ?

**Comment by Marec4** [comment] 2020-02-04 19:15
Hey, sorry for the delay. Will check in the morning and report

**Comment by t3nshi** [comment] 2020-02-04 19:18
Thanks a lot! let me know

**Comment by Marec4** [comment] 2020-02-05 06:58
Seems much better now. Only Amount Reserved is still cut off

![Screenshot_20200205-085630_Token_Wallet 1](https://user-images.githubusercontent.com/25827470/73818223-91638700-47f5-11ea-9033-810e5323ca46.jpg)

**Comment by t3nshi** [comment] 2020-02-05 13:38
Ok. Thanks for the feedback. May I ask, what resolution does your screen have? I will need to tweak a bit further this page

**Comment by Marec4** [comment] 2020-02-05 13:41
720*1280 according to gsmarena

**Closed as completed** 2020-02-07 15:34 UTC
Labels: bug
